### ISSUE TITLE
PostgreSQL and JSONField for serialized_data

### ISSUE THREAD

**Issue by Kub-AT** [grantmcconnaughey/django-field-history#2]
I t's just my suggestion but I think, for PostgreSQL you shoud use fields like **HStoreField** or **JSONField** for **serialized_data** field.

- Django < 1.8.x: models.TextField()
- Django = 1.8.x: from django.contrib.postgres.fields import HStoreField https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#hstorefield
- Django >= 1.9.x and PostgreSQL >= 9.4: from django.contrib.postgres.fields import JSONField https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield

**Comment by grantmcconnaughey** [comment]
Hey @Kub-AT, I've thought about doing this but I don't want to make this package Postgres-only. I haven't seen any examples of dynamically changing the type of field on a model based on which database backend is used, or which specific version (9.4+) of a backend is being used. If you have any suggestions then let me know.
