### ISSUE TITLE
All fields

### ISSUE THREAD

**Issue by stiig** [grantmcconnaughey/django-field-history#4]
Please add keyword for track all fields, like a `__all__`

**Comment by stiig** [comment]
Or maybe add keyword argument `exclude=[]`, and if argument given, then track all field, without exclude

**Comment by grantmcconnaughey** [comment]
I'm not sure about this one. The whole point of django-field-history is to just track the history of a few fields, not every field on a model. If you want to track changes to an entire model then django-reversion or django-simple-history are your best bet.

**Comment by grantmcconnaughey** [comment]
I'm going to close this issue because I just don't think it fits with what this package is trying to accomplish. Thank you for opening the issue! :+1:
