### ISSUE TITLE
Serializing changes of parent model fields

### ISSUE THREAD

**Issue by ramusus** [grantmcconnaughey/django-field-history#5]
I faced with the problem, when I want to track fields of parent model using `django-field-history` app i'm unable to save the value of the field [due to the problem of how Django serializers works](https://docs.djangoproject.com/en/1.9/topics/serialization/#inherited-models). They all returns copy just of tables, but working with inherited models we need to search among parent fields too.
As result `data` field doesn't contains any fields values.

**Comment by grantmcconnaughey** [comment]
Fixed in #6
